# ====================================================================
# SIGEA-GTT: Infraestrutura como Código (IaC) para Render Web Service
# ====================================================================
services:
  - type: web
    name: sigea-gtt-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: ohio
    branch: main
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:+UseSerialGC -Xss512k -XX:MaxRAMPercentage=75.0 -Dfile.encoding=UTF-8"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
